### ISSUE TITLE
it seems can't work

### ISSUE THREAD

**Issue by EnderAvaritia** [ManlyMarco/RoundAndRoundTrain-TranslationHelper#1]
![image](https://user-images.githubusercontent.com/84321282/188361026-1d040852-7f14-4364-9696-28522b063445.png)
![image](https://user-images.githubusercontent.com/84321282/188361054-d0026935-f36d-4c89-be8f-a5daa75aef8d.png)

**Comment by ManlyMarco** [comment]
I'll release a translation pack with this plugin later today.

**Comment by EnderAvaritia** [comment]
thank you

**Comment by EnderAvaritia** [comment]
where may I get the pack

**Comment by EnderAvaritia** [comment]
> I'll release a translation pack with this plugin later today.

how can I get the pack
may I have a more detailed  course to use this tool

**Comment by ManlyMarco** [comment]
https://www.mediafire.com/file/cn9r5tuwdqe9krh/ENG_MTL_UNC_Trainer_v1_for_RoundAndRoundTrain_RJ326532.zip
More information and modpacks for other games: https://www.patreon.com/posts/71611562

**Comment by EnderAvaritia** [comment]
> https://www.mediafire.com/file/cn9r5tuwdqe9krh/ENG_MTL_UNC_Trainer_v1_for_RoundAndRoundTrain_RJ326532.zip More information and modpacks for other games: https://www.patreon.com/posts/71611562

my card can't support offer the subscribe

**Comment by ManlyMarco** [comment]
What? Just download from the first link, it's free.

**Comment by EnderAvaritia** [comment]
> What? Just download from the first link, it's free.

thanks
I also want to find other games  , but I can't offer the subscribe with my card.

**Comment by ManlyMarco** [comment]
The post will be free in 2 days, you can simply wait until then.

**Comment by EnderAvaritia** [comment]
> The post will be free in 2 days, you can simply wait until then.

ok
